//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domin.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domin.Resource.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the customer’s category of less than 10 kilos so that the process can be completed successfully....!.
        /// </summary>
        internal static string ClintPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("ClintPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the password...!.
        /// </summary>
        internal static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match...!.
        /// </summary>
        internal static string ComparePasswordcomferm {
            get {
                return ResourceManager.GetString("ComparePasswordcomferm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل القيود المحاسبية .
        /// </summary>
        internal static string LBAddAccountingRestriction {
            get {
                return ResourceManager.GetString("LBAddAccountingRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companie Type Work En.
        /// </summary>
        internal static string LbCompanieTypeWorkEn {
            get {
                return ResourceManager.GetString("LbCompanieTypeWorkEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسائل العملاء.
        /// </summary>
        internal static string LBMyCustomerMessage {
            get {
                return ResourceManager.GetString("LBMyCustomerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد التنبيهات.
        /// </summary>
        internal static string LBMyEmailAlartSetting {
            get {
                return ResourceManager.GetString("LBMyEmailAlartSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن أن تتجاوز عدد الاحرف المدخلة عن 100 حرف .
        /// </summary>
        internal static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 1000 characters...!.
        /// </summary>
        internal static string MaxLength1000 {
            get {
                return ResourceManager.GetString("MaxLength1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 20 characters...!.
        /// </summary>
        internal static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 2000 characters...!.
        /// </summary>
        internal static string MaxLength2000 {
            get {
                return ResourceManager.GetString("MaxLength2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 25 characters...!.
        /// </summary>
        internal static string MaxLength25 {
            get {
                return ResourceManager.GetString("MaxLength25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 300 characters...!.
        /// </summary>
        internal static string MaxLength300 {
            get {
                return ResourceManager.GetString("MaxLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى عدد أحرف يمكن أدخاله هو 3000 حرف .. !.
        /// </summary>
        internal static string MaxLength3000 {
            get {
                return ResourceManager.GetString("MaxLength3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد الاقصى لعدد الحروف المدخلة يجب ان لا يتجاوز 50 حرف يرجى إعادة المحاولة لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string MaxLength50 {
            get {
                return ResourceManager.GetString("MaxLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 500 characters...!.
        /// </summary>
        internal static string MaxLength500 {
            get {
                return ResourceManager.GetString("MaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not be less than one character, and the # symbol can be used to indicate the same page....!.
        /// </summary>
        internal static string MinLength1 {
            get {
                return ResourceManager.GetString("MinLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not be less than 3 characters....!.
        /// </summary>
        internal static string MinLength3 {
            get {
                return ResourceManager.GetString("MinLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not be less than 5 characters....!.
        /// </summary>
        internal static string MinLength5 {
            get {
                return ResourceManager.GetString("MinLength5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of characters for the password must be at least 5 characters.
        /// </summary>
        internal static string MinLengthPassword5 {
            get {
                return ResourceManager.GetString("MinLengthPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password for the process to complete successfully...!.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number...!.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include your email..!.
        /// </summary>
        internal static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered format must be the email format...!.
        /// </summary>
        internal static string RegisterEmailError {
            get {
                return ResourceManager.GetString("RegisterEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email...!.
        /// </summary>
        internal static string RegisterEmaillogin {
            get {
                return ResourceManager.GetString("RegisterEmaillogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include full name.....!.
        /// </summary>
        internal static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user permission for the process to complete successfully..!.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال البيان الخاص بسند الشراء لتتم العملية بنجاح...!.
        /// </summary>
        internal static string StatementPurchase {
            get {
                return ResourceManager.GetString("StatementPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الزر باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string TitleButtonAr {
            get {
                return ResourceManager.GetString("TitleButtonAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الزر باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string TitleButtonEn {
            get {
                return ResourceManager.GetString("TitleButtonEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان الثاني  باللغة العربية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string TitleTwoAr {
            get {
                return ResourceManager.GetString("TitleTwoAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج العنوان الثاني باللغة الانكليزية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string TitleTwoEn {
            get {
                return ResourceManager.GetString("TitleTwoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the user name...!.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج اسم الحساب الرئيسي لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlAccountName {
            get {
                return ResourceManager.GetString("VlAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادراج رقم الحساب  الخاص بالموظف  لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlAccountNumber {
            get {
                return ResourceManager.GetString("VlAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج منشأ المهمة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlAddedBy {
            get {
                return ResourceManager.GetString("VlAddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the address for the process to complete successfully.
        /// </summary>
        internal static string VlAddres {
            get {
                return ResourceManager.GetString("VlAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company address for the process to complete successfully...!.
        /// </summary>
        internal static string VlAddresCompany {
            get {
                return ResourceManager.GetString("VlAddresCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlAddressAr {
            get {
                return ResourceManager.GetString("VlAddressAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج العنوان باللغة الانكليزية لتتم العملية بنجاح ...1.
        /// </summary>
        internal static string VlAddressEn {
            get {
                return ResourceManager.GetString("VlAddressEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم المنطقة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlAreaName {
            get {
                return ResourceManager.GetString("VlAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the exchange rate in the local currency on the black market for the process to complete successfully....!.
        /// </summary>
        internal static string VlBlackMarketExchangeRate {
            get {
                return ResourceManager.GetString("VlBlackMarketExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlBuilding.
        /// </summary>
        internal static string VlBuilding {
            get {
                return ResourceManager.GetString("VlBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please inclode the Catch Receipt.
        /// </summary>
        internal static string VlCatchReceiptNo {
            get {
                return ResourceManager.GetString("VlCatchReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدخال  الفئة باللغة العربية لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string VlCategoryNameAr {
            get {
                return ResourceManager.GetString("VlCategoryNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدخال الفئة باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlCategoryNameEn {
            get {
                return ResourceManager.GetString("VlCategoryNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج اسم المدينة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlCitieName {
            get {
                return ResourceManager.GetString("VlCitieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the customer&apos;s delivery price so that the process is completed successfully...!.
        /// </summary>
        internal static string VlClintDelivery {
            get {
                return ResourceManager.GetString("VlClintDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the customer’s category of more than 10 kilos so that the process can be completed successfully....!.
        /// </summary>
        internal static string VlClintPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlClintPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the local currency code for the operation to complete successfully..!.
        /// </summary>
        internal static string Vlcode {
            get {
                return ResourceManager.GetString("Vlcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رمز المادة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlCodeItem {
            get {
                return ResourceManager.GetString("VlCodeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدرج حالة الشركة الفعلية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlCompanieTypeWorkAr {
            get {
                return ResourceManager.GetString("VlCompanieTypeWorkAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the actual company status in Arabic for the process to be successful...!.
        /// </summary>
        internal static string VlCompanieTypeWorkEn {
            get {
                return ResourceManager.GetString("VlCompanieTypeWorkEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company&apos;s delivery price so that the process can be completed successfully...!.
        /// </summary>
        internal static string VlCompanyDelivery {
            get {
                return ResourceManager.GetString("VlCompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company&apos;s delivery price so that the process can be completed successfully...!.
        /// </summary>
        internal static string VlCompanyDescription {
            get {
                return ResourceManager.GetString("VlCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company name for the process to complete successfully...!.
        /// </summary>
        internal static string VlCompanyName {
            get {
                return ResourceManager.GetString("VlCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم الشركة بالعربي لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlCompanyNameAr {
            get {
                return ResourceManager.GetString("VlCompanyNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the company name in English for the process to be completed successfully...!.
        /// </summary>
        internal static string VlCompanyNameEn {
            get {
                return ResourceManager.GetString("VlCompanyNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the category higher than 10 kilograms received from the shipping company so that the process can be completed successfully....!.
        /// </summary>
        internal static string VlCoPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the category of less than 10 kilograms received from the shipping company so that the process can be completed successfully....!.
        /// </summary>
        internal static string VlCoPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the country for the process to complete successfully...!.
        /// </summary>
        internal static string VlCountry {
            get {
                return ResourceManager.GetString("VlCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string VlCurrency {
            get {
                return ResourceManager.GetString("VlCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سقف المديونية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlDebtlimit {
            get {
                return ResourceManager.GetString("VlDebtlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم شركة التوصيل لتتم العلية بنجاح ...!.
        /// </summary>
        internal static string VlDeliveryCompanie {
            get {
                return ResourceManager.GetString("VlDeliveryCompanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج عنوان شركة التوصيل  لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlDeliveryCompanieAddress {
            get {
                return ResourceManager.GetString("VlDeliveryCompanieAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include descreption for the process to complete successfully...!.
        /// </summary>
        internal static string VlDescreption {
            get {
                return ResourceManager.GetString("VlDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج الوصف لتتم العملية بنجاح.
        /// </summary>
        internal static string VlDescription {
            get {
                return ResourceManager.GetString("VlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج الوصف باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlDescriptionAr {
            get {
                return ResourceManager.GetString("VlDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a description of the link between the customer and the pricing. The process is completed successfully...!.
        /// </summary>
        internal static string VlDescriptionClint {
            get {
                return ResourceManager.GetString("VlDescriptionClint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة وصف الشركة باللغة الانكليزية لتتم العملية بنجاح .
        /// </summary>
        internal static string VlDescriptionEn {
            get {
                return ResourceManager.GetString("VlDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the order description for the process to complete successfully.
        /// </summary>
        internal static string VlDescriptionOrder {
            get {
                return ResourceManager.GetString("VlDescriptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اميل التواصل لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string VlEmaiContact {
            get {
                return ResourceManager.GetString("VlEmaiContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the nickname for the process to complete successfully..!.
        /// </summary>
        internal static string VlEmail {
            get {
                return ResourceManager.GetString("VlEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج إميل الشركة لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlEmailCompany {
            get {
                return ResourceManager.GetString("VlEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج البريد الاكتروني الصحيح لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlEmailMessage {
            get {
                return ResourceManager.GetString("VlEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج البريد الاكتروني الخاص بالمدير التنفيذي لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlEmailOner {
            get {
                return ResourceManager.GetString("VlEmailOner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج الاميل الخاص بشركة التوصيل لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlEmilCompanie {
            get {
                return ResourceManager.GetString("VlEmilCompanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج البريد الاكتروني  الخاص بالمدير التنفيذي لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlEmilOner {
            get {
                return ResourceManager.GetString("VlEmilOner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج عنوان  الخاص بالموظف لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlEmployeeAddress {
            get {
                return ResourceManager.GetString("VlEmployeeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج البريد الاكتروني الخاص بالموظف لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlEmployeeEmail {
            get {
                return ResourceManager.GetString("VlEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم الموظف كاملا لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlEmployeeFullname {
            get {
                return ResourceManager.GetString("VlEmployeeFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج رقم الهاتف الخاص بالموظف لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlEmployeePhone {
            get {
                return ResourceManager.GetString("VlEmployeePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج فئة المصروفات لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlExpenseCategory {
            get {
                return ResourceManager.GetString("VlExpenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج رابط الفيس بوك لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlFaceBoock {
            get {
                return ResourceManager.GetString("VlFaceBoock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please include FAQ to complete successfully...!.
        /// </summary>
        internal static string VlFAQ {
            get {
                return ResourceManager.GetString("VlFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlFloor.
        /// </summary>
        internal static string VlFloor {
            get {
                return ResourceManager.GetString("VlFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the exchange rate in foreign currency for the process to complete successfully...!.
        /// </summary>
        internal static string VlForeignCurrency {
            get {
                return ResourceManager.GetString("VlForeignCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج الاسم كاملا لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlFullName {
            get {
                return ResourceManager.GetString("VlFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the exchange rate in the local currency for the process to complete successfully...!.
        /// </summary>
        internal static string VlGlobalExchangeRate {
            get {
                return ResourceManager.GetString("VlGlobalExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج فترة السماح لتتم العملية بنجاح .....!.
        /// </summary>
        internal static string VlGracePeriod {
            get {
                return ResourceManager.GetString("VlGracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج رابط الانستجرام لتتم العملية بنجاح .
        /// </summary>
        internal static string VlInstagram {
            get {
                return ResourceManager.GetString("VlInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم المادة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlItemName {
            get {
                return ResourceManager.GetString("VlItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج المسمى الوظيفي الخاص بالموظف لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlJobTitle {
            get {
                return ResourceManager.GetString("VlJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include List FAQ for the process to complete successfully...!.
        /// </summary>
        internal static string VlListFAQ {
            get {
                return ResourceManager.GetString("VlListFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the exchange rate in the local currency for the process to complete successfully...!.
        /// </summary>
        internal static string VllocalCurrency {
            get {
                return ResourceManager.GetString("VllocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج رابط العنوان على خارئط جوجل لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlMabs {
            get {
                return ResourceManager.GetString("VlMabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج الرسالة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlMessage {
            get {
                return ResourceManager.GetString("VlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Message Description for the process to complete successfully...!.
        /// </summary>
        internal static string VlMessageDescription {
            get {
                return ResourceManager.GetString("VlMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الرسالة لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlMessageTitle {
            get {
                return ResourceManager.GetString("VlMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رقم الهاتف  لتمم العملية بنجاح ...!.
        /// </summary>
        internal static string VlMobile {
            get {
                return ResourceManager.GetString("VlMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlMoblie.
        /// </summary>
        internal static string VlMoblie {
            get {
                return ResourceManager.GetString("VlMoblie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادراج اسم الشركة باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlNameCompanyAr {
            get {
                return ResourceManager.GetString("VlNameCompanyAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج اسم الشركة باللغة الأنكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlNameCompanyEn {
            get {
                return ResourceManager.GetString("VlNameCompanyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج اسم المدير التنفيذي لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlNameOner {
            get {
                return ResourceManager.GetString("VlNameOner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the nickname for the process to complete successfully..!.
        /// </summary>
        internal static string VlNikeNAme {
            get {
                return ResourceManager.GetString("VlNikeNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlOffice.
        /// </summary>
        internal static string VlOffice {
            get {
                return ResourceManager.GetString("VlOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج اسم المدير التنفيذي لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlOnerName {
            get {
                return ResourceManager.GetString("VlOnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم المدير التنفيذي بالشركة باللغة العربية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlOnerNameAr {
            get {
                return ResourceManager.GetString("VlOnerNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the name of the company&apos;s CEO in English for the process to be completed successfully....!.
        /// </summary>
        internal static string VlOnerNameEn {
            get {
                return ResourceManager.GetString("VlOnerNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج هاتف المدير التنفيذي لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlOnerPhone {
            get {
                return ResourceManager.GetString("VlOnerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Password Email for the process to complete successfully...!.
        /// </summary>
        internal static string VlPasswordEmail {
            get {
                return ResourceManager.GetString("VlPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج طريقة الدفع باللغة العربية لتتم العملية بنجاح...!.
        /// </summary>
        internal static string VlPaymentMethodAr {
            get {
                return ResourceManager.GetString("VlPaymentMethodAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج طريقة الدفع باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlPaymentMethodEn {
            get {
                return ResourceManager.GetString("VlPaymentMethodEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Phone.
        /// </summary>
        internal static string VlPhone {
            get {
                return ResourceManager.GetString("VlPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the phone number for the process to complete successfully....!.
        /// </summary>
        internal static string VlPhoneCompany {
            get {
                return ResourceManager.GetString("VlPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رقم الهاتف لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlPhonenumber {
            get {
                return ResourceManager.GetString("VlPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج هاتف التواصل لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlPhonenumberContact {
            get {
                return ResourceManager.GetString("VlPhonenumberContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج هاتف المدير التنفيذي لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlPhoneOner {
            get {
                return ResourceManager.GetString("VlPhoneOner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج السعر الخاص بالمنتج لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string Vlprice {
            get {
                return ResourceManager.GetString("Vlprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادخال السعر لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlPricing {
            get {
                return ResourceManager.GetString("VlPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة اسم المنتج باللغة العربية لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string VlProductNameAr {
            get {
                return ResourceManager.GetString("VlProductNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة اسم المنتج باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlProductNameEn {
            get {
                return ResourceManager.GetString("VlProductNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Amount.
        /// </summary>
        internal static string VlProfitAmount {
            get {
                return ResourceManager.GetString("VlProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Project Description for the process to complete successfully...!.
        /// </summary>
        internal static string VlProjectDescription {
            get {
                return ResourceManager.GetString("VlProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج وصف المشروع باللغة العربيةلتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlProjectDescriptionAr {
            get {
                return ResourceManager.GetString("VlProjectDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Project Name for the process to complete successfully...!.
        /// </summary>
        internal static string VlProjectName {
            get {
                return ResourceManager.GetString("VlProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم المشروع باللغة العربية  لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlProjectNameAr {
            get {
                return ResourceManager.GetString("VlProjectNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Project Types for the process to complete successfully...!.
        /// </summary>
        internal static string VlProjectTypes {
            get {
                return ResourceManager.GetString("VlProjectTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج نوع المشروع باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlProjectTypesAr {
            get {
                return ResourceManager.GetString("VlProjectTypesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال  تاريخ سند الشراء لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string VlPurchaseDate {
            get {
                return ResourceManager.GetString("VlPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج سعر الشراء لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlPurchasePrice {
            get {
                return ResourceManager.GetString("VlPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدخال الكمية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlQuantity {
            get {
                return ResourceManager.GetString("VlQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج تقيم الشركة لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string VlRating {
            get {
                return ResourceManager.GetString("VlRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a bond number for the process to complete successfully...!.
        /// </summary>
        internal static string VlReceiptNo {
            get {
                return ResourceManager.GetString("VlReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the receipt statement for the process to be completed successfully....!.
        /// </summary>
        internal static string VlReceiptStatment {
            get {
                return ResourceManager.GetString("VlReceiptStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة الطلب باللغة العربية  لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlRequestsAr {
            get {
                return ResourceManager.GetString("VlRequestsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the request in English for the process to be completed successfully...!.
        /// </summary>
        internal static string VlRequestsEn {
            get {
                return ResourceManager.GetString("VlRequestsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الطلب لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlRequestsTitelAr {
            get {
                return ResourceManager.GetString("VlRequestsTitelAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the title of the request related to the task for the process to be completed successfully....!.
        /// </summary>
        internal static string VlRequestsTitelEn {
            get {
                return ResourceManager.GetString("VlRequestsTitelEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the amount for the transaction to complete successfully..!.
        /// </summary>
        internal static string VlResivedMony {
            get {
                return ResourceManager.GetString("VlResivedMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string VlShippingAddress {
            get {
                return ResourceManager.GetString("VlShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج الوصف القصير باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlShortDescriptionAr {
            get {
                return ResourceManager.GetString("VlShortDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج الوصف القصير باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlShortDescriptionEn {
            get {
                return ResourceManager.GetString("VlShortDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Smtp Server for the process to complete successfully...!.
        /// </summary>
        internal static string VlSmtpServer {
            get {
                return ResourceManager.GetString("VlSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج اختصاص المورد لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlSpecialization {
            get {
                return ResourceManager.GetString("VlSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال بيان سند الصرف لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlStatement {
            get {
                return ResourceManager.GetString("VlStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج البيان لتتم العملية بنجاح .
        /// </summary>
        internal static string VlStatementPurchase {
            get {
                return ResourceManager.GetString("VlStatementPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Street.
        /// </summary>
        internal static string VlStreet {
            get {
                return ResourceManager.GetString("VlStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى اسم المورد لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlSupplierName {
            get {
                return ResourceManager.GetString("VlSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Task Status for the process to complete successfully...!.
        /// </summary>
        internal static string VlTaskStatus {
            get {
                return ResourceManager.GetString("VlTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج حالة المهمة لتتم العملية بنجاح .....!.
        /// </summary>
        internal static string VlTaskStatusAr {
            get {
                return ResourceManager.GetString("VlTaskStatusAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlTitle.
        /// </summary>
        internal static string VlTitle {
            get {
                return ResourceManager.GetString("VlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleAr {
            get {
                return ResourceManager.GetString("VlTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الزر باللغة العربية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlTitleButtonAr {
            get {
                return ResourceManager.GetString("VlTitleButtonAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الزر باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleButtonEn {
            get {
                return ResourceManager.GetString("VlTitleButtonEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the task title in English. The process is successful...!.
        /// </summary>
        internal static string VlTitleEn {
            get {
                return ResourceManager.GetString("VlTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادراج العنوان الخامس  باللغة العربية لتتم العملية  بنجاح ...!.
        /// </summary>
        internal static string VlTitlefiveAr {
            get {
                return ResourceManager.GetString("VlTitlefiveAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج العنوان الخامس باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitlefiveEn {
            get {
                return ResourceManager.GetString("VlTitlefiveEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج العنوان الرابع باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleForAr {
            get {
                return ResourceManager.GetString("VlTitleForAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج العنوان الرابع باللغة الانكليزية لتتم العملية بنجاح ..!.
        /// </summary>
        internal static string VlTitleForEn {
            get {
                return ResourceManager.GetString("VlTitleForEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العناون الاول  باللغة العربية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlTitleOneAr {
            get {
                return ResourceManager.GetString("VlTitleOneAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان  الاول  باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleOneEn {
            get {
                return ResourceManager.GetString("VlTitleOneEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الأدخال باللغة الانكليزية  مسبقا يرجى التأكد وإعادة المحاولة لاحقا ....!.
        /// </summary>
        internal static string VLTitleOneEnDoplceted {
            get {
                return ResourceManager.GetString("VLTitleOneEnDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the appropriate address in the shipping category for the process to complete successfully...!.
        /// </summary>
        internal static string VlTitleShipping {
            get {
                return ResourceManager.GetString("VlTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال  العنوان الثالث باللغة العربية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlTitleThreAr {
            get {
                return ResourceManager.GetString("VlTitleThreAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال العنوان الثالث باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleThreEn {
            get {
                return ResourceManager.GetString("VlTitleThreEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان الثاني باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleTwoAr {
            get {
                return ResourceManager.GetString("VlTitleTwoAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان الثاني باللغة الانكليزية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTitleTwoEn {
            get {
                return ResourceManager.GetString("VlTitleTwoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج الاجمالي لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTotal {
            get {
                return ResourceManager.GetString("VlTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered format must be the email format for the process to complete successfully...!.
        /// </summary>
        internal static string VLTypEmail {
            get {
                return ResourceManager.GetString("VLTypEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the nickname for the process to complete successfully..!.
        /// </summary>
        internal static string VlTypesCompanies {
            get {
                return ResourceManager.GetString("VlTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Types Of Message  for the process to complete successfully...!.
        /// </summary>
        internal static string VlTypesOfMessage {
            get {
                return ResourceManager.GetString("VlTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Types Of Request for the process to complete successfully...!.
        /// </summary>
        internal static string VlTypesOfRequest {
            get {
                return ResourceManager.GetString("VlTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Type Of Task for the process to complete successfully...!.
        /// </summary>
        internal static string VlTypesOfTask {
            get {
                return ResourceManager.GetString("VlTypesOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج فئة المهمة باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlTypesOfTaskAr {
            get {
                return ResourceManager.GetString("VlTypesOfTaskAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the system type for the process to complete successfully..!.
        /// </summary>
        internal static string VlTypeSystem {
            get {
                return ResourceManager.GetString("VlTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the type of delivery system for the process to complete successfully...!.
        /// </summary>
        internal static string VlTypeSystemDelivery {
            get {
                return ResourceManager.GetString("VlTypeSystemDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج الوحدة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlUnit {
            get {
                return ResourceManager.GetString("VlUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رابط التوجيه باللغة العربية لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlUrlButtonAr {
            get {
                return ResourceManager.GetString("VlUrlButtonAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج رابط التوجيه باللغة الانكليزية لتتم العملية بنجاح ....!.
        /// </summary>
        internal static string VlUrlButtonEn {
            get {
                return ResourceManager.GetString("VlUrlButtonEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رابط الفيس بوك الخاص بالشركة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlUrlFacebook {
            get {
                return ResourceManager.GetString("VlUrlFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رابط الانستجرام الخاص بالشركة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlUrlInstagram {
            get {
                return ResourceManager.GetString("VlUrlInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج موقع الشركة لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string Vlwebsite {
            get {
                return ResourceManager.GetString("Vlwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رقم الواتس الخاص بالتواصل لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlWhatsupnumberContact {
            get {
                return ResourceManager.GetString("VlWhatsupnumberContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج رابط اليو تيوب لتتم العملية بنجاح ...!.
        /// </summary>
        internal static string VlYouTube {
            get {
                return ResourceManager.GetString("VlYouTube", resourceCulture);
            }
        }
    }
}
